version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BloedeHuhn
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    image: poke-backend
    build:
      context: ./PokeBackend
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pokemon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: BloedeHuhn
    depends_on:
      postgres:
        condition: service_healthy

  flutter-frontend:
    image: poke-frontend
    build:
      context: ./Poke_Frontend
      dockerfile: Dockerfile-flutter
    ports:
      - "8081:80"
    environment:
      FLUTTER_APP_URL: http://localhost:8081
